version: "2"

linters:
  enable:
    - gosec
    - revive
    - gocritic
    - cyclop
    - misspell
  settings:
    cyclop:
      max-complexity: 20
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - gosec
